### ISSUE TITLE
Problema com o balão com o detalhe do log

### ISSUE THREAD

**Issue by eduardosilva** [ITLab-Academy/LogHoras#1]
Quando você exibe o balão com o detalhe do log e no calendário você muda o mês, as vezes o balão não some e fica visivel apontando para o "nada".

Abaixo a evidencia.

![evidencia](https://cloud.githubusercontent.com/assets/427080/8875295/87fdfbf4-31ee-11e5-9e1c-c4fd3ffc02c9.PNG)

**Comment by eklam** [comment]
Problema resolvido na versão de 2015-07-26
