### ISSUE TITLE
O título esta quebrando linha mesmo tendo espaço

### ISSUE THREAD

**Issue by eduardosilva** [ITLab-Academy/LogHoras#11]
O título da página Apontamento de Horas esta quebrando linha mesmo tendo espaço na tela ao abrir no celular. Acredito que o problema seja o col-xs-9 na div do título acredito que possa ser trocado para col-xs-12.

![evidencia](https://cloud.githubusercontent.com/assets/427080/8911981/f4a2883c-3465-11e5-99f0-c13a72cb811a.PNG)

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.
