### ISSUE TITLE
remover o tooltip e trazer os ícones para o item

### ISSUE THREAD

**Issue by luidones** [ITLab-Academy/LogHoras#15]
conforme imagem abaixo, trazer os icones para o item no calendário

![image](https://cloud.githubusercontent.com/assets/6014310/8937902/a5e25dae-3531-11e5-993e-87f53da51b9a.png)

**Comment by RenanStigliani** [comment]
@CamillaMV

Implementar a ideia sugerida para logs que tenham espaço (no mínimo 1 hora de duração)
