### ISSUE TITLE
permitir cadastrar intervalos menores que 15 minutos

### ISSUE THREAD

**Issue by luidones** [ITLab-Academy/LogHoras#17]
Profissionais alocados tem que conviver com catracas.
Alguns clientes podem querer bater os horários indicados com os registrados na portaria.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.

**Comment by marceloneias** [comment]
Conforme alinhamos, a diretiva da diretoria é realizar o arredondamento (15 minutos) para facilitar cálculos e fechamentos, caso haja questionamento de clientes a diretoria alinhará com o cliente esta regra IT Lab.
