### ISSUE TITLE
calendar deixa selecionar intervalo entre dias, mas sistema não permite

### ISSUE THREAD

**Issue by luidones** [ITLab-Academy/LogHoras#18]
o sistema de log não permite começar uma tarefa que começa num dia e terminar no outro.
porém o componente de calendar deixa. verificar a possibilidade no componente de travar isso.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.

**Comment by RenanStigliani** [comment]
Resolvido na versão de 13/08/2015
