### ISSUE TITLE
Ícone de editar log não aparece

### ISSUE THREAD

**Issue by eklam** [ITLab-Academy/LogHoras#2]
Ícone de editar log não aparece:

![icone](https://cloud.githubusercontent.com/assets/3126251/8875962/eef79122-31f2-11e5-9e5b-daa32863a7dc.png)

**Comment by leolana** [comment]
Corrigido, aguarde a próxima versão.

**Comment by eklam** [comment]
Problema resolvido na versão de 2015-07-26

**Comment by eduardosilva** [comment]
Ainda a icones que não estão sendo carregados.

![evidencia](https://cloud.githubusercontent.com/assets/427080/8912635/5761dc1c-346a-11e5-90ae-d321ac0424b1.PNG)

**Comment by RenanStigliani** [comment]
Resolvido na versão de 13/08/2015
