### ISSUE TITLE
Mensagem de descrição inválida.

### ISSUE THREAD

**Issue by luidones** [ITLab-Academy/LogHoras#22]
Recebo um aviso de descrição inválida constantemente.
Se for uma restrição de quantidade mínima de palavras seria interessante dizer na mensagem de erro. Ex: "A descrição deve conter um mínimo de X palavras."

**Comment by marceloneias** [comment]
A ideia desta validação é forçar a termos descrições melhores de log, a regra é bem simples e exige o mínimo, mas se explicitarmos a regra para o usuário ele saberá como burlar e manterá uma descrição pobre.

**A regra está sendo alterada, a nova versão que está para subir nesta semana será menos exigente, para as descrições que você costuma colocar acredito que não terá problemas.**

**Comment by RenanStigliani** [comment]
Dúvida sanada
