### ISSUE TITLE
Permitir apertar ESC para cancelar o drag'n drop

### ISSUE THREAD

**Issue by luidones** [ITLab-Academy/LogHoras#24]
As vezes arrasto sem querer e não lembro aonde estava o bloco, o sistema poderia cancelar o "move" ao apertar a tecla ESC.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.

**Comment by RenanStigliani** [comment]
@CamillaMV, pode conferir se essa melhoria foi implementada na versão atual? Nos meus testes, ao apertar o ESC o move não foi cancelado

**Comment by CamillaMV** [comment]
Eu acrescentei esta função depois de gerar a versão atual. Estará disponível na próxima versão.
