### ISSUE TITLE
Alterar a regra de restrição de data para permitir apontamentos "futuros"

### ISSUE THREAD

**Issue by marceloneias** [ITLab-Academy/LogHoras#25]
Nesta nova versão o sistema está restringindo apontamento referente a datas > hora atual, porém, o sistema deve permitir apontamentos de datas futuras até 3 dias após hoje.

Exemplo:

**Apontamentos Permitidos** (considerando data de hoje = 13/08/2015.
- 13/08/2015
- 14/08/2015
- 15/08/2015
- 16/08/2015 (até 23:59).

**Apontamentos NÃO Permitidos** (considerando data de hoje = 13/08/2015.
-   >= 17/08/2015 à partir das 00:00

**IMPORTANTE:** A restrição de apontamento referente a datas anteriores ao dia de hoje deve ser mantida como está.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.

**Comment by RenanStigliani** [comment]
Conforme solicitação do hirota foi alterado de 3 para 15 dias
