### ISSUE TITLE
Reduzir obrigatoriedade de palavras na validação da descrição do log

### ISSUE THREAD

**Issue by marceloneias** [ITLab-Academy/LogHoras#26]
Neste momento o sistema exige **3 espaços** (portanto, 4 palavras) na descrição do log como sendo obrigatório para permitir o apontamento, esta regra deve ser ajustada para exibir no mínimo **2 espaços** (portanto, 3 palavras) na descrição do log.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.
