### ISSUE TITLE
Configuração para desativar arredontamento automático. por usuario

### ISSUE THREAD

**Issue by LuizCrivelli** [ITLab-Academy/LogHoras#27]
Tenho muitos apontamentos em minutos quebrados (por vezes de até 5 - 10 minutos por atendimento)

O 23:59 ele deixa. rss

Acho uma boa deixar este arredontamento como um parametro.

**Comment by RenanStigliani** [comment]
@LuizCrivelli 

Isso foi alinhado direto com a diretoria, de acordo com o Marcelo Neias:

> Conforme alinhamos, a diretiva da diretoria é realizar o arredondamento (15 minutos) para facilitar cálculos e fechamentos, caso haja questionamento de clientes a diretoria alinhará com o cliente esta regra IT Lab.

Issue relacionado: https://github.com/ITLab-Academy/LogHoras/issues/17
