### ISSUE TITLE
Campos de data e hora estão sendo limpos após seleção e duplicação.

### ISSUE THREAD

**Issue by washington-guedes** [ITLab-Academy/LogHoras#31]
Quando eu seleciono as horas para um novo lançamento e em seguida vou na opção de duplicar de outro lançamento, os campos de data e hora estão sendo limpos.

Acho que poderia ter uma condição no botão de duplicar:
- Se existir uma seleção para um novo lançamento
- então quando clicar no botão de duplicação não precisa limpar campos de data e hora.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.
