### ISSUE TITLE
Busca no campo de módulos

### ISSUE THREAD

**Issue by GustavoChristians** [ITLab-Academy/LogHoras#33]
Atualmente a busca aplicada no campo módulos, não permite a busca por nomes de clientes e nem de projetos.

Se possível alterar a regra de busca para facilitar a busca.

**Comment by RenanStigliani** [comment]
Quando a busca encontrar o nome de um Projeto, exibir todos os Módulos abaixo do mesmo.
Quando encontrar o nome de um Cliente, exibir todos os Projetos (e Módulos) abaixo do Cliente

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.
