### ISSUE TITLE
Problemas com a descrição do apontamento

### ISSUE THREAD

**Issue by GustavoChristians** [ITLab-Academy/LogHoras#35]
Existem algumas descrições de log que necessitam de mais espaço para a visualização de sua descrição.

Se possível, adicionar uma textarea podermos visualizar o conteúdo da descrição do apontamento de forma mais clara.

**Comment by marceloneias** [comment]
Gustavo, ok, obrigado pela sugestão, vamos planejar a implementação.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.
