### ISSUE TITLE
horas restantes dos módulos ou uma cor diferente nos modulos sem horas disponiveis

### ISSUE THREAD

**Issue by LuizCrivelli** [ITLab-Academy/LogHoras#36]
teria como fazer alguma diferenciação entre os modulos que ainda estão em aberto (que constem horas a serem utilizadas) com os modulos que ja estao fechados por não terem mais como ser utilizados ?

Como sugestão , alterar a cor do texto na combo módulo para cinza ou apresentar o tempo restante no mesmo combo do modulo.
![capture](https://cloud.githubusercontent.com/assets/13859935/9637529/c230ecb6-5177-11e5-8b31-827dbb99e5a3.PNG)

**Comment by marceloneias** [comment]
Crivelli, a implementação de algum **indicador se o módulo possui ou não verba disponível** (verba, e não horas) está autorizada, já a implementação da **exibição das horas disponíveis não foi autorizada**.

Vamos planejar a implementação deste indicador (módulo possui ou não verba disponível para apontamento de log).
