### ISSUE TITLE
Total de horas trabalhadas por dia e por semana no caledário visão mensal e semanal.

### ISSUE THREAD

**Issue by LuizCrivelli** [ITLab-Academy/LogHoras#37]
Sinto falta de linhas totalizadoras diarias no calendário (visão "semana") informando o total de horas trabalhadas por dia.  segue uma imagem com o total trabalhado ao lado do dia semana

![capture1](https://cloud.githubusercontent.com/assets/13859935/9648977/c7c72cce-51c4-11e5-8496-6c281b218480.PNG)

O mesmo poderia ter na visão mensal, o total de horas trabalhadas por semana (sugestão,ao lado do calendário, uma coluna totalizadora ) e o total diário ao lado do número indicativo do dia,segue uma imagem com o total trabalhado ao lado do dia.

![capture2](https://cloud.githubusercontent.com/assets/13859935/9649057/ee74c8e4-51c5-11e5-9dc0-ce42962a8091.PNG)

Pois para eu obter estas informações tenho que ficar alternando de visoes semanais / diarias e mensais , onde em cada visão me apresenta apenas o total da visão.

**Comment by marceloneias** [comment]
Ótima sugestão Crivelli, vamos planejar para implementar.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.

**Comment by LuizCrivelli** [comment]
E o Total de horas Semanais na visão mensal ?

**Comment by RenanStigliani** [comment]
Realmente, ficou faltando o Total Semanal, eu conferi apenas pelas imagens
