### ISSUE TITLE
mensagem de boas vindas apresenta o domínio e o login

### ISSUE THREAD

**Issue by LuizCrivelli** [ITLab-Academy/LogHoras#38]
Acredito que a mensagem de boas vindas no canto superior deva apresentar o nome ou somente o login, sem o dominio.

![capture3](https://cloud.githubusercontent.com/assets/13859935/9649343/07832ab6-51ca-11e5-8a97-e980b78ba156.PNG)

**Comment by marceloneias** [comment]
Vamos planejar para ajustar, retirando o domínio, deixando somente o nome do usuário.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.

**Comment by LuizCrivelli** [comment]
agora sim ficou bom heim . 

utilize replace itlab\ para '' e não substring

![image](https://cloud.githubusercontent.com/assets/13859935/10269442/5b181cca-6aae-11e5-983b-57ca95d332a5.png)

**Comment by RenanStigliani** [comment]
Também aconteceu comigo e com o Rodolfo Hafez

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.
