### ISSUE TITLE
Alterar a cor da borda do apontamento no calendário e descricao da atividade

### ISSUE THREAD

**Issue by LuizCrivelli** [ITLab-Academy/LogHoras#39]
Quando se apontam atividades seguidas do mesmo modulo (e categorias diferentes), os apontamentos são da mesma cor , porém a visualização fica muito ruim por não haver nenhuma diferenciação entre um apontamento e outro. segue imagem com sugestão de uma cor de borda diferente.  
![capture4](https://cloud.githubusercontent.com/assets/13859935/9701088/5a41add0-53f1-11e5-816a-c5619403cb46.PNG)

Outra melhoria que pode ser incluída no calendário é a descrição da atividade . como apontei na imagem . 
Para lermos cada descrição temos que obrigatoriamente clicar em cada atividade. mesmo que haja um belo espaço no quadro apontado.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.

**Comment by RenanStigliani** [comment]
@CamillaMV,

Faltou a parte de aproveitar o espaço disponível para exibir a descrição da atividade quando disponível. Cadastrei isso na isseu #50 para poder fechar essa
