### ISSUE TITLE
Erro selecione um módulo (quando ele já está selecionado visualmente)

### ISSUE THREAD

**Issue by marceloneias** [ITLab-Academy/LogHoras#4]
O sistema impede a gravação do log e emite a mensagem pedindo para selecionar um módulo, sendo que o mesmo já está selecionado "visualmente".

Passos para reproduzir:
1. Feche e abra a aplicação (ao entrar, repare que o módulo está em branco, não selecionado).
2. Role a barra de rolagem para baixo (até o ponto que o box do módulo desapareça) e depois role a barra de rolagem para cima novamente (até o ponto que o box do módulo apareça novamente), repare que o módulo agora está selecionado.
3. Preencha os demais campos mantendo o módulo que está selecionado.
4. Clique no botão Gravar, o sistema vai impedir a gravação do log e emitirá a mensagem pedindo para selecionar um módulo.

**Comment by eklam** [comment]
@marceloneias pode efetuar o teste novamente? Não consegui reproduzir o problema

**Comment by marceloneias** [comment]
@eklam efetuei os testes, não ocorreu mais.
