### ISSUE TITLE
Botão "Salvar" quando se está editando um log poderia trocar a descrição para "Atualizar"

### ISSUE THREAD

**Issue by LuizCrivelli** [ITLab-Academy/LogHoras#40]
Quando se está editando um log , sugiro alguma modificação no botão "Salvar" para atualizar
ou utilizar cores diferentes , mas acho que é mais fácil trocar somente o texto.
, ex: 
![capture5](https://cloud.githubusercontent.com/assets/13859935/9701137/e3ca716c-53f2-11e5-8811-20c36aad0333.PNG)
![capture6](https://cloud.githubusercontent.com/assets/13859935/9701138/e6946bbe-53f2-11e5-904b-a12a5aa4b1a7.PNG)

Exemplo que a edição não está clara, vc clica em um apontamento para editar , ele carrega os dados para edição no topo e mostra o tootip que está sendo editado , porem ao arrastar o log para um horario diferente , o tooltip indicativo de edição some, o log é salvo no novo horário, mas o log ainda permanece em edição sem nenhum aviso que o botão salvar lá no topo atualizará o log ou se salvará um novo

**Comment by RenanStigliani** [comment]
@CamillaMV 

No novo deixar **Inlcuir**
Na edição deixar **Alterar**
