### ISSUE TITLE
Sistema calculando total de apontamento de horas de forma diferente (ou errada) do sistema antigo

### ISSUE THREAD

**Issue by eduardosilva** [ITLab-Academy/LogHoras#43]
Ta dando diferença nos calculos dos totais.

![evidencia01](https://cloud.githubusercontent.com/assets/427080/9776564/246a056c-5730-11e5-958e-43457aea772f.PNG)
![evidencia02](https://cloud.githubusercontent.com/assets/427080/9776565/246c6294-5730-11e5-8913-9a614e24e556.PNG)

**Comment by RenanStigliani** [comment]
Edu, o sistema antigo mosta a somatória em decimal, o sistema novo mostra em horas e minutos.

Ou seja, 150 horas e 15 minutos. Como 15 minutos corresponde à 25% de 1 hora, no sistema antigo é exibido 150,25 (150 horas, + 0,25 de hora).

Lembro também que na hora de efetuar o cálculo de valor financeiro, deve se usar o valor em decimal. 

Podemos propor uma melhoria para facilitar esse cálculo

**Comment by eduardosilva** [comment]
O maluco como assim você fecha minha issue sem saber se eu concordo ou não
com seu discurso?
Eu entendi o seu ponto mas segue abaixo as minhas considerações:
1. Essa mudança foi feita e o pessoal não foi notificado, isso é um big
   problema.
2. A gente não usa o total em horas e minutos pra nada agora o total em
   decimal usamos pelo menos uma vez por mês, depois de todas as comodidades
   inseridas no sistema não faz sentido eu ter que fazer conta para gerar o
   faturamente mesmo essa conta sendo simples.

**Comment by eduardosilva** [comment]
Alinhei com o @MarceloNeias e esse item deve ser implementado.

**Comment by marceloneias** [comment]
Conforme alinhado com a diretoria, transformar todos os totais de horas em formato decimal.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.

**Comment by RenanStigliani** [comment]
@CamillaMV,

Alguns totais ainda não estão em decimal:

![pms apontamento log de horas](https://cloud.githubusercontent.com/assets/3126251/10193539/22cc0838-675a-11e5-9ff6-943edb2ec4d0.png)

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.
