### ISSUE TITLE
Quando duplica o log no calendário em modo "mês" o logo esta sendo gravado duas vezes

### ISSUE THREAD

**Issue by eduardosilva** [ITLab-Academy/LogHoras#44]
![evidencia](https://cloud.githubusercontent.com/assets/427080/9904719/550d29a8-5c56-11e5-8f1c-a4355ad425fc.PNG)

**Comment by RenanStigliani** [comment]
Também acabei gravando log duplicado. Enquanto eu arrasta o seleção para definir o horário, outro programa abriu "na frente", na hora que voltei no sistema de Log, a caixa de seleção ainda estava send arrastada (mesmo sem eu segurar o botão do mouse), ao clicar no calendário, dois logs foram criados, um com o horário da caixa de seleção, e um novo, com apenas 15 minutos:

![logduplicado](https://cloud.githubusercontent.com/assets/3126251/10024614/79a57504-612e-11e5-8bb5-c91c5be4a001.png)

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.
