### ISSUE TITLE
LOG DUPLICADO

### ISSUE THREAD

**Issue by LuizCrivelli** [ITLab-Academy/LogHoras#46]
A Flavia me reportou log duplicado , porem eu somente estou utilizando o novo apontamento de log . 
segue o id do log para analise 245919 e  245920 data : 23/09/2015 22:00:00 até  23/09/2015 22:00:00

Veja se está salvando em lote com verificação de log antes de cada instrução ou se está sendo feita a verificação antes de todas as instruções.
Caso a verificação seja feira antes de todas as instruções , se por um acaso o lote tiver log duplicado , o sistema irá salvar os dois sem barrar a duplicidade.

**Comment by marceloneias** [comment]
@LuizCrivelli , identificamos o bug que ocorre somente em um determinado cenário, bem específico, já estamos providenciando a correção e nos próximos dias vamos liberar uma nova versão. Obrigado novamente pelo report do bug.

**Comment by RenanStigliani** [comment]
Corrigido junto com o #44
