### ISSUE TITLE
Erro ao visualizar um apontamento de log que não termina em hora cheia e 1/4 de hora

### ISSUE THREAD

**Issue by marceloneias** [ITLab-Academy/LogHoras#48]
O sistema "trava" (loading não some) quando se tenta visualizar um apontamento de log que não termina em hora cheia (XX:00) e 1/4 de hora (XX:15 / XX:30 / XX:45).

Passos para reproduzir:
- Através do calendário, apontar um log que termina às 00h00 (repare que o sistema muda o horário de término para 23h59).
- Recarregue a tela, repare que o loading não some e dá um erro de javascript no console do browser.

Se mover este mesmo apontamento, o sistema manterá a proporção de horas, ou seja, não terminando em 1/4 de hora (1 minuto a menos na verdade) e nesta situação o loading também não some.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.
