### ISSUE TITLE
Nova regra de negócio: Restrição para o apontamento de log

### ISSUE THREAD

**Issue by marceloneias** [ITLab-Academy/LogHoras#5]
O sistema deverá restringir o apontamento de log conforme regra abaixo

Só é permitido apontar o log cuja data do log esteja:
- Regra 1: Entre os últimos 7 dias à partir do dia do apontamento.
- Regra 2: Esteja dentro do mesmo mês da data do apontamento (esta Regra 2 não é aplicável ao dia 1º de cada mês, onde neste caso aplicá-se somente a Regra 1).

Exemplos:

**Apontamentos permitidos:**

- Data do apontamento: 02, 03, 04, 05, 06 ou 07
- Data de log permitida apontar: entre o dia 01 (do mês do apontamento) e o dia do apontamento.

- Data do apontamento: 08
- Data de log permitida apontar: entre o dia 02 (do mês do apontamento) e o dia do apontamento (08).

- Data do apontamento: 15
- Data de log permitida apontar: entre o dia 09 (do mês do apontamento) e o dia do apontamento (15).

- Data do apontamento: 31
- Data de log permitida apontar: entre o dia 25 (do mês do apontamento) e o dia do apontamento (31).

- Data do apontamento: 01
- Data de log permitida apontar: entre o dia 26 (do mês anterior do apontamento - caso o mês anterior termine no dia 31) e o dia do apontamento (01).

**Apontamentos não permitidos:**
- Dia do apontamento: 01
- Data do log: 15 do mês anterior

- Dia do apontamento: 02
- Data do log: 30 do mês anterior

- Dia do apontamento: 15
- Data do log: 01 do mês do apontamento.

**Comment by RenanStigliani** [comment]
Resolvido na versão de 13/08/2015
