### ISSUE TITLE
Impedir apontamentos de log que passe de um dia para outro

### ISSUE THREAD

**Issue by marceloneias** [ITLab-Academy/LogHoras#51]
1. Implementar regra no backend que impeça apontamentos que passe de um dia para outro (todo apontamento deve ser dentro de um mesmo dia - data/hora início e data/hora fim).
2. Na visão semana, impedir criar log apontamento que passe de um dia para outro, hoje esta sendo possível realizando os seguintes passos:
   - Criar um apontamento normal (exemplo: das 15h00 às 18h00).
   - Ir para a visão semana.
   - No calendário, arrastar o apontamento realizado para passar de um dia para outro.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.
