### ISSUE TITLE
Total em horas no lançamento não bate  9:30 as 10:45 = 00:15 minutos

### ISSUE THREAD

**Issue by LuizCrivelli** [ITLab-Academy/LogHoras#52]
![image](https://cloud.githubusercontent.com/assets/13859935/10564480/7d8ca69a-7594-11e5-876a-dcc5900c7dd5.png)

**Comment by eduardosilva** [comment]
Parece que o problema só ocorre quando utiliza o controle de horas e minutos. Quando o valor é digitado na caixa de texto o cálculo é realizado da forma corretora.

![evidencia](https://cloud.githubusercontent.com/assets/427080/10607113/12725868-7716-11e5-9aac-48b14af35842.png)

**Comment by CamillaMV** [comment]
Não conseguimos reproduzir o bug.
Crivelli, pode verificar se ainda está ocorrendo e em que momento?

**Comment by LuizCrivelli** [comment]
deve tes sido por causa do horário de verão . pois ocorreu no domingo
