### ISSUE TITLE
Regra do primeiro dia útil.

### ISSUE THREAD

**Issue by washington-guedes** [ITLab-Academy/LogHoras#54]
Hoje (03/10), primeiro dia útil do mês, não deveria permitir salvar logs dos últimos 7 dias?

**Comment by marceloneias** [comment]
Sim, deveria, é bug e vamos corrigir, obrigado pelo report.

**Comment by marceloneias** [comment]
Bug corrigido, será publicada uma nova versão do sistema ainda neste mês.
