### ISSUE TITLE
Duplicar não está mais permitindo alterar a descrição.

### ISSUE THREAD

**Issue by washington-guedes** [ITLab-Academy/LogHoras#55]
Eu costumava clicar no botão de duplicar de um lançamento já existente para já vir o Módulo e a Categoria selecionados, então eu digitava a nova descrição e selecionava a área para inserir o log.

Agora, após fazer os passos acima, a nova descrição digitada não está sendo salva, no lugar está indo a descrição do log que eu cliquei em duplicar.

**Comment by itlabacademy** [comment]
Washington, isso em qual visão? Mês, semana ou dia?

**Comment by washington-guedes** [comment]
Visão Semana

**Comment by marceloneias** [comment]
Segui os passos e para mim o comportamento foi diferente.
Por favor, grave um gif animado reproduzindo este problema e me retorne pra que eu veja, pode utilizar o programa ScreenToGif (http://www.screentogif.com) para gravar.

**Comment by washington-guedes** [comment]
Bem legal esse `screentogif`, não conhecia.
Segue:
![gif](https://user-images.githubusercontent.com/13021912/39366826-95852ddc-4a24-11e8-8864-a29eb53f586d.gif)

**Comment by marceloneias** [comment]
Ok, consegui reproduzir o bug, vou providenciar a correção.

Uma alterantiva para você fazer isso até a correção é, clique em duplicar, já selecione no calendário o dia/horário que você quer (o sistema irá registrar o log exatamente igual) e em seguida clique em editar o novo log e altere a descrição.

**Comment by marceloneias** [comment]
Washington, o problema foi solucionado, por favor, realize alguns testes e nos retorne se está ok agora.
Observação: Para garantir que você estará na nova versão, limpe o cache do navegador.
