### ISSUE TITLE
Não está carregando o Log após ter trocado a senha

### ISSUE THREAD

**Issue by washington-guedes** [ITLab-Academy/LogHoras#56]
Hoje troquei a senha (a cada três meses preciso trocar a senha), e o Log não está mais carregando:
![image](https://user-images.githubusercontent.com/13021912/39524900-fe7fa522-4e09-11e8-987f-acfaf9922776.png)

**Comment by marceloneias** [comment]
Washington, não foi um problema específico com você, foi geral, acredito que algo relacionado a infra-estrutura, pelo que vi agora o sistema já está funcionando.

**Comment by itlabacademy** [comment]
From: Eudes Machado Furlan 
Sent: quarta-feira, 2 de maio de 2018 10:24
To: Eduardo Alexandre Lourenço da Silva <eduardo.silva@itlab.com.br>
Cc: Marcelo Néias <marcelo.neias@itlab.com.br>
Subject: RE: PMS Fora

Olá Edu,

O problema foi resolvido.
Uma atualização do Windows exigiu a reinicialização automática do servidor e, ao voltar, o serviço do SQL Server não tinha subido.

Abs.
