### ISSUE TITLE
Trocar do ícone de exclusão no tooltip

### ISSUE THREAD

**Issue by leolana** [ITLab-Academy/LogHoras#6]
Avaliar a troca do ícone de exclusão (x) que aparece no tooltip quando o usuário clica em cima do log para uma lixeira. Porquê da maneira que está pode confundir o usuário com a ação de fechar o tooltip.
![tooltip](https://cloud.githubusercontent.com/assets/6184662/8905813/c6ec9e62-343f-11e5-8ecf-f7ba78959684.png)

**Comment by eklam** [comment]
Muito importante! Realmente está confundindo!

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.

**Comment by RenanStigliani** [comment]
Resolvido na versão de 13/08/2015
