### ISSUE TITLE
Data errada quando visualizando período Mês

### ISSUE THREAD

**Issue by eklam** [ITLab-Academy/LogHoras#8]
Na visão calen'dario, é exibido o dia da semana, porém, quando se está visualizando todo o mês, além do dia da semana está sendo exibido tambem o dia do primeiro Domingo, Segunda, etc.

Exemplo:

![untitled](https://cloud.githubusercontent.com/assets/3126251/8906151/950d16ee-3442-11e5-98a9-59c35a5cf8cf.png)

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.

**Comment by RenanStigliani** [comment]
Resolvido na versão de 13/08/2015
