### ISSUE TITLE
Separar o botão salvar das outras opções possíveis

### ISSUE THREAD

**Issue by eduardosilva** [ITLab-Academy/LogHoras#9]
Ao clicar no botão salvar sempre é necessário escolher entre Gravar ou Novo. O ideal seria sempre gravar e todos as outras opções abrirem ao clicar na seta.

**Comment by CamillaMV** [comment]
Feito em desenvolvimento.

**Comment by RenanStigliani** [comment]
Resolvido na versão de 13/08/2015
